### ISSUE TITLE
[pipy package] Any possibility to update the Pipy repo?

### ISSUE THREAD

**Issue by caduzeraa** [jupyterhub/nativeauthenticator#123] opened 2020-11-12 14:35 UTC
The last update went on feb 20. Would be realy nice to update the repo as the new features comes out.

**Comment by lambdaTotoro** [comment] 2020-11-12 14:44
This question (not a bug) needs input from @leportella. We have made some reasonable progress since end of February, what are your criteria for new releases?

**Comment by caduzeraa** [comment] 2020-11-12 14:51
Some bugs that were fixed, new features that were released. And the package is outdated, so it would be nice to have the pipy package updated. I'm using with the pipy and just realised it's outdated now :s . Just a suggestion.

**Comment by lambdaTotoro** [comment] 2020-11-14 13:43
We have a new version on Pypi now, closing. 

https://pypi.org/project/jupyterhub-nativeauthenticator/

**Closed** 2020-11-14 13:43 UTC
Labels: question
