### ISSUE TITLE
failed login for admin user

### ISSUE THREAD

**Issue by ByungSun12** [jupyterhub/nativeauthenticator#138] opened 2021-02-17 03:52 UTC
#### Actual behaviour

![스크린샷 2021-02-17 오후 12 44 54](https://user-images.githubusercontent.com/65884594/108153149-f1d21780-711d-11eb-89aa-498ac82d2847.png)

### How to reproduce

1. Intall JupyterHub
2. Execution with jupyterhub_config.py
3. Login admin user

### Your personal set up

 - OS: Ubuntu 18.04
 
 - Version(s):
   - jupyterhub 1.3.0
   - python 3.8.5
 

- <details><summary>Full environment</summary>

```
alembic @ file:///home/conda/feedstock_root/build_artifacts/alembic_1612370625906/work
anyio @ file:///home/conda/feedstock_root/build_artifacts/anyio_1612745534218/work/dist
argon2-cffi @ file:///tmp/build/80754af9/argon2-cffi_1613037097816/work
async-generator @ file:///home/ktietz/src/ci/async_generator_1611927993394/work
attrs @ file:///tmp/build/80754af9/attrs_1604765588209/work
Babel @ file:///home/conda/feedstock_root/build_artifacts/babel_1605182336601/work
backcall @ file:///home/ktietz/src/ci/backcall_1611930011877/work
bcrypt==3.2.0
bleach @ file:///tmp/build/80754af9/bleach_1612211392645/work
blinker==1.4
brotlipy==0.7.0
certifi==2020.12.5
certipy==0.1.3
cffi @ file:///tmp/build/80754af9/cffi_1613246945912/work
chardet @ file:///tmp/build/80754af9/chardet_1607706746162/work
conda==4.9.2
conda-package-handling @ file:///tmp/build/80754af9/conda-package-handling_1603018141399/work
cryptography @ file:///tmp/build/80754af9/cryptography_1613400861696/work
decorator @ file:///home/ktietz/src/ci/decorator_1611930055503/work
defusedxml @ file:///home/ktietz/src/ci_mi/defusedxml_1612808095953/work
entrypoints==0.3
idna @ file:///home/linux1/recipes/ci/idna_1610986105248/work
importlib-metadata @ file:///tmp/build/80754af9/importlib-metadata_1602276842396/work
ipykernel @ file:///home/conda/feedstock_root/build_artifacts/ipykernel_1611268310209/work/dist/ipykernel-5.4.3-py3-none-any.whl
ipython @ file:///tmp/build/80754af9/ipython_1612212923938/work
ipython-genutils @ file:///tmp/build/80754af9/ipython_genutils_1606773439826/work
ipywidgets @ file:///tmp/build/80754af9/ipywidgets_1610481889018/work
jedi==0.17.0
Jinja2 @ file:///tmp/build/80754af9/jinja2_1612213139570/work
json5 @ file:///home/conda/feedstock_root/build_artifacts/json5_1600692310011/work
jsonschema @ file:///tmp/build/80754af9/jsonschema_1602607155483/work
jupyter==1.0.0
jupyter-client @ file:///tmp/build/80754af9/jupyter_client_1601311786391/work
jupyter-console @ file:///tmp/build/80754af9/jupyter_console_1598884538475/work
jupyter-core @ file:///tmp/build/80754af9/jupyter_core_1612213311222/work
jupyter-server @ file:///home/conda/feedstock_root/build_artifacts/jupyter_server_1612496705427/work
jupyter-telemetry @ file:///home/conda/feedstock_root/build_artifacts/jupyter_telemetry_1605173804246/work
jupyterhub==1.3.0
jupyterhub-nativeauthenticator==0.0.7
jupyterlab @ file:///home/conda/feedstock_root/build_artifacts/jupyterlab_1612296988614/work
jupyterlab-pygments @ file:///tmp/build/80754af9/jupyterlab_pygments_1601490720602/work
jupyterlab-server @ file:///home/conda/feedstock_root/build_artifacts/jupyterlab_server_1612473182866/work
jupyterlab-widgets @ file:///tmp/build/80754af9/jupyterlab_widgets_1609884341231/work
Mako @ file:///home/conda/feedstock_root/build_artifacts/mako_1610659158978/work
MarkupSafe==1.1.1
mistune==0.8.4
nbclassic @ file:///home/conda/feedstock_root/build_artifacts/nbclassic_1610352513187/work
nbclient @ file:///tmp/build/80754af9/nbclient_1602783176460/work
nbconvert @ file:///tmp/build/80754af9/nbconvert_1601914830498/work
nbformat @ file:///tmp/build/80754af9/nbformat_1610738111109/work
nest-asyncio @ file:///tmp/build/80754af9/nest-asyncio_1606153767164/work
notebook @ file:///tmp/build/80754af9/notebook_1611340975709/work
oauthlib==3.0.1
onetimepass==1.0.1
packaging @ file:///tmp/build/80754af9/packaging_1611952188834/work
pamela==1.0.0
pandocfilters @ file:///tmp/build/80754af9/pandocfilters_1605120460739/work
parso @ file:///tmp/build/80754af9/parso_1607623074025/work
pexpect @ file:///tmp/build/80754af9/pexpect_1605563209008/work
pickleshare @ file:///tmp/build/80754af9/pickleshare_1606932040724/work
prometheus-client @ file:///tmp/build/80754af9/prometheus_client_1606344362066/work
prompt-toolkit @ file:///tmp/build/80754af9/prompt-toolkit_1602688806899/work
ptyprocess @ file:///tmp/build/80754af9/ptyprocess_1609355006118/work/dist/ptyprocess-0.7.0-py2.py3-none-any.whl
pycosat==0.6.3
pycparser @ file:///tmp/build/80754af9/pycparser_1594388511720/work
pycurl==7.43.0.6
Pygments @ file:///tmp/build/80754af9/pygments_1610565767015/work
PyJWT @ file:///home/conda/feedstock_root/build_artifacts/pyjwt_1610910308735/work
pyOpenSSL @ file:///tmp/build/80754af9/pyopenssl_1608057966937/work
pyparsing @ file:///home/linux1/recipes/ci/pyparsing_1610983426697/work
pyrsistent @ file:///tmp/build/80754af9/pyrsistent_1600141720057/work
PySocks @ file:///tmp/build/80754af9/pysocks_1605305779399/work
python-dateutil @ file:///home/ktietz/src/ci/python-dateutil_1611928101742/work
python-editor==1.0.4
python-json-logger @ file:///home/conda/feedstock_root/build_artifacts/python-json-logger_1602545356084/work
pytz @ file:///home/conda/feedstock_root/build_artifacts/pytz_1612179539967/work
pyzmq==20.0.0
qtconsole @ file:///tmp/build/80754af9/qtconsole_1612458529756/work
QtPy==1.9.0
requests @ file:///tmp/build/80754af9/requests_1608241421344/work
ruamel-yaml==0.15.87
ruamel.yaml.clib @ file:///home/conda/feedstock_root/build_artifacts/ruamel.yaml.clib_1605537770387/work
Send2Trash @ file:///tmp/build/80754af9/send2trash_1607525499227/work
sip==4.19.13
six @ file:///tmp/build/80754af9/six_1605205327372/work
sniffio @ file:///home/conda/feedstock_root/build_artifacts/sniffio_1610318319305/work
SQLAlchemy @ file:///tmp/build/80754af9/sqlalchemy_1612467554095/work
sudospawner==0.5.2
terminado==0.9.2
testpath @ file:///home/ktietz/src/ci/testpath_1611930608132/work
tornado @ file:///tmp/build/80754af9/tornado_1606942300299/work
tqdm @ file:///tmp/build/80754af9/tqdm_1611857934208/work
traitlets @ file:///home/ktietz/src/ci/traitlets_1611929699868/work
urllib3 @ file:///tmp/build/80754af9/urllib3_1611694770489/work
wcwidth @ file:///tmp/build/80754af9/wcwidth_1593447189090/work
webencodings==0.5.1
widgetsnbextension==3.5.1
zipp @ file:///tmp/build/80754af9/zipp_1604001098328/work
```
</details>

- <details><summary>Configuration</summary>

```python
# jupyterhub_config.py
c.JupyterHub.spawner_class = 'sudospawner.SudoSpawner'
c.Spawner.default_url = '/lab'
c.JupyterHub.ip = '0.0.0.0'
c.JupyterHub.hub_port = 8888
c.JupyterHub.port = 8080
c.JupyterHub.authenticator_class = 'nativeauthenticator.NativeAuthenticator'

c.Authenticator.admin_users = {'aiadmin',} # or your admin user for testing
c.Authenticator.open_signup = True

import subprocess
def set_notebook_dir(spawner):
    import os
    username = spawner.user.name
    to_m_dir = os.path.join("/data/", username)
    os.makedirs(to_m_dir, mode=0o777, exist_ok=True)
    _ = subprocess.run(["chown", f"{username}:jupyterhub", "-R", to_m_dir])

def pre_spawn_hook(spawner):
    set_notebook_dir(spawner)
    username = spawner.user.name
    try:
        pwd.getpwnam(username)
        #subprocess.check_call(['useradd', '-ms', '/bin/bash', username])
    except Exception as e:
        subprocess.check_call(['useradd', '-ms', '/bin/bash', username])

c.Spawner.pre_spawn_hook = pre_spawn_hook
c.Spawner.notebook_dir = "/data/{username}"
```
</details>

- <details><summary>Logs</summary>

```
# logs in jupyterhub
...
[I 2021-02-17 03:41:41.401 JupyterHub proxy:399] Adding default route for Hub: / => http://127.0.0.1:8888
03:41:41.402 [ConfigProxy] info: 200 GET /api/routes
03:41:41.403 [ConfigProxy] info: Adding route / -> http://127.0.0.1:8888
03:41:41.403 [ConfigProxy] info: Route added / -> http://127.0.0.1:8888
03:41:41.403 [ConfigProxy] info: 201 POST /api/routes/
[I 2021-02-17 03:41:41.404 JupyterHub app:2739] JupyterHub is now running at http://0.0.0.0:8080/
[I 2021-02-17 03:41:46.192 JupyterHub log:181] 200 GET /hub/login (@192.168.210.73) 25.33ms
[W 2021-02-17 03:41:51.082 JupyterHub base:763] Failed login for aiadmin
```
</details>

**Comment by lambdaTotoro** [comment] 2021-02-23 18:51
Hello @ByungSun12, thanks for your report. I can see that you entered the admin user into the configuration. But did you also _sign up_ that user with a password? You didn't mention it in your steps to reproduce. Otherwise, what password are you entering?

**Comment by lambdaTotoro** [comment] 2021-09-27 20:05
I tested this again today and if you enter the admin username into `admin_users` and sign up that account, login works perfectly fine. I'm closing this issue as **cannot reproduce**.

**Closed by lambdaTotoro** 2021-09-27 20:05 UTC
Labels: bug
