### ISSUE TITLE
issue with hub/authorize page and user login

### ISSUE THREAD

**Issue by sudi007** [jupyterhub/nativeauthenticator#104] opened 2020-03-17 20:02 UTC
Hi 

i having an issue with hub/authorize  page when i go to authorize a user  i get an error 403 forbidden and then also when i try to log in with a user created  i get the following error 
500 : Internal Server Error
Error in Authenticator.pre_spawn_start: KeyError "getpwnam(): name not found: 'amit'"
You can try restarting your server from the home page.
is there a way to resolve this

**Comment by meeseeksmachine** [comment] 2020-03-18 09:53
This issue has been mentioned on **Jupyter Community Forum**. There might be relevant details there:

https://discourse.jupyter.org/t/setup-jupyterhub-setup-with-nativeauthenticator/3652/2

**Comment by leportella** [comment] 2020-03-29 13:42
Which version of Jupyterhub and Native authenticator are you using?

**Comment by sudi007** [comment] 2020-03-29 14:11
Am using the latest ver of jupyterhub 6.0.3 with latest build of nativeauthenticator And also was able to fix the authorizing portion  but the problem is when i authorize a new user and log in with there user name and password i get the following error

500 : Internal Server Error
Error in Authenticator.pre_spawn_start: KeyError "getpwnam(): name not found: 'amit

**Comment by lambdaTotoro** [comment] 2020-04-24 17:09
We ran into a similar problem recently, because someone forgot to also create user accounts on the machine running JupyterHub. So the users were authorized and could log in, but didn't have a home directory or a corresponding account on the machine, which produced the error. Adding those resolved the error.

@sudi007 , could you confirm that you have user accounts for the users that are experiencing this problem?

**Comment by lambdaTotoro** [comment] 2020-10-30 20:31
I've reproduced this and I'm pretty sure it's just the above (missing an account on the local machine), I'll close this for now.

**Closed by lambdaTotoro** 2020-10-30 20:31 UTC

**Comment by sudi007** [comment] 2020-10-30 20:40
Thanks for closing it i totally forgot i had left it open
Thanks
